PASOS EN ORACLE XEPDB1

DB_URL=jdbc:oracle:thin:@//localhost:1521/XEPDB1;DB_USER=crud_user;DB_PASSWORD=Crud123

-- Crea un usuario nuevo en Oracle llamado crud_user
CREATE USER crud_user

-- Define la contraseña del usuario
IDENTIFIED BY Crud123

-- Indica que el tablespace por defecto será "users"
-- Ahí se guardarán sus objetos si no especificas otro
DEFAULT TABLESPACE users

-- Le da espacio ilimitado en el tablespace "users"
-- Esto permite que pueda crear tablas y guardar datos sin que Oracle lo bloquee por falta de cuota
QUOTA UNLIMITED ON users;

-- Da permiso para iniciar sesión en la base de datos
GRANT CREATE SESSION,

      -- Permite crear tablas en su propio esquema
      CREATE TABLE,

      -- Permite crear secuencias, útiles para generar IDs
      CREATE SEQUENCE,

      -- Permite crear vistas
      CREATE VIEW

-- Estos permisos se asignan al usuario crud_user
TO crud_user;



-- =========================================
-- BASE DE DATOS
-- =========================================

--TABLA USUARIOS
CREATE TABLE usuarios (

    -- ID único del usuario
    -- NUMBER: tipo numérico en Oracle
    -- GENERATED BY DEFAULT AS IDENTITY: genera el valor automáticamente
    -- PRIMARY KEY: clave primaria, no se repite y no puede ser nula
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nombre de usuario para iniciar sesión
    -- VARCHAR2(50): texto variable de hasta 50 caracteres
    -- NOT NULL: obligatorio
    -- UNIQUE: no se puede repetir
    username VARCHAR2(50) NOT NULL UNIQUE,

    -- Contraseña del usuario
    -- VARCHAR2(255): texto variable de hasta 255 caracteres
    -- Se usa largo porque normalmente aquí se guarda el hash de la contraseña,
    -- no la contraseña en texto plano
    -- NOT NULL: obligatorio
    pass VARCHAR2(255) NOT NULL,

    -- Estado del usuario
    -- NUMBER(1): número de 1 dígito
    -- Se usa como bandera: 1 = activo, 0 = inactivo
    -- DEFAULT 1: si no mandas valor, queda activo por defecto
    enabled NUMBER(1) DEFAULT 1
);

--TABLA ROLES
CREATE TABLE roles (

    -- ID único del rol
    -- NUMBER autogenerado
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nombre del rol
    -- VARCHAR2(50): texto variable
    -- NOT NULL: obligatorio
    -- UNIQUE: no se puede repetir, por ejemplo no puede haber dos ADMIN
    nombre VARCHAR2(50) NOT NULL UNIQUE
);

--TABLA USUARIO ROL
CREATE TABLE usuario_rol (

    -- ID del usuario
    -- NUMBER: porque debe ser del mismo tipo que usuarios.id
    -- NOT NULL: obligatorio
    id_usuario NUMBER NOT NULL,

    -- ID del rol
    -- NUMBER: porque debe ser del mismo tipo que roles.id
    -- NOT NULL: obligatorio
    id_rol NUMBER NOT NULL,

    -- PRIMARY KEY compuesta
    -- Evita que se repita la misma combinación usuario-rol
    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),

    -- Llave foránea hacia usuarios(id)
    -- Garantiza que el usuario exista
    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id),

    -- Llave foránea hacia roles(id)
    -- Garantiza que el rol exista
    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES roles(id)
);

--TABLA CLIENTES
-- =========================================
-- TABLA: clientes
-- Tabla principal del CRUD
-- =========================================
CREATE TABLE clientes (

    -- ID único del cliente
    -- NUMBER autogenerado
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nombre del cliente
    -- VARCHAR2(100): texto variable hasta 100 caracteres
    -- NOT NULL: obligatorio
    nombre VARCHAR2(100) NOT NULL,

    -- Apellido del cliente
    -- VARCHAR2(100): texto variable hasta 100 caracteres
    -- NOT NULL: obligatorio
    apellido VARCHAR2(100) NOT NULL,

    -- Correo electrónico
    -- VARCHAR2(150): texto variable
    -- UNIQUE: no se repite
    correo VARCHAR2(150) UNIQUE,

    -- Teléfono del cliente
    -- VARCHAR2(20): texto variable
    -- Se usa texto y no NUMBER porque puede llevar guiones,
    -- espacios o símbolo +
    telefono VARCHAR2(20),

    -- Fecha de creación del registro
    -- DATE: guarda fecha y hora en Oracle
    -- DEFAULT SYSDATE: pone automáticamente la fecha/hora actual
    fecha_creacion DATE DEFAULT SYSDATE
);


INSERT INTO CLIENTES (nombre, apellido, correo, telefono)
VALUES ('Juan', 'Cortez', 'juan.cortez@ign.sv', '77489874');

INSERT INTO CLIENTES (nombre, apellido, correo, telefono)
VALUES ('Paola', 'Perez', 'paola.perez@hotmail.com', '74879874');


INSERT INTO USUARIO_ROL(id_usuario,id_rol)
VALUES(1,1);

INSERT INTO USUARIO_ROL(id_usuario,id_rol)
VALUES(2,2);
COMMIT;


SELECT * FROM USUARIO_ROL;


SELECT * FROM USUARIOS;


SELECT 
    a.ID AS ID_USUARIO,
    a.USERNAME AS USUARIO,
    a.PASS AS CONTRASE,
    a.ENABLED AS ACTIVO,
    c.NOMBRE AS ROL
FROM USUARIOS a
INNER JOIN USUARIO_ROL b
    ON a.ID = b.ID_USUARIO
INNER JOIN ROLES c
    ON c.ID = b.ID_ROL;

--DEPENDENCIAS MAVEN SPRING 3.5.13
--JDK 21
Web → Spring Web
SQL → Spring Data JPA
I/O → Validation
SQL → Oracle Driver


--PROYECTO EN BLANCO ANGULAR
npm exec --package @angular/cli@21 ng new crud_2026 --routing=false --style=css --skip-git

npm start -- --host 0.0.0.0
